### ISSUE TITLE
psql Style backslash commands

### ISSUE THREAD

**Issue by psychemedia** [catherinedevlin/ipython-sql#113]
What's the trick for running psql-style "backslash" meta-commands commands (`\d`)?

Looking at the code , it appears to look for a `\\` as the first part of a magic command.

But if I try things like `%sql \d` or `%sql \\d` I get an error such as:

```
(psycopg2.ProgrammingError) syntax error at or near "\"
LINE 1: \\d
        ^
 [SQL: '\\\\d']
```

**Comment by ddanieltan** [comment]
I am facing the same issue. Appreciate guidance on the correct syntax to use a meta command.

**Comment by psychemedia** [comment]
The updated docs suggest that `%sql \d` is the fomulation, but that throws an error for me:

```
%sql \d

(psycopg2.ProgrammingError) syntax error at or near "\"
LINE 1: \d
        ^
 [SQL: '\\d']
```

**Comment by ddanieltan** [comment]
I have verified that my ipython-sql is at version 0.3.8 which I believe is the latest version. I am still facing the same error when using psql meta commands.
