### ISSUE TITLE
Do CTEs (common table expressions) not work with SQL Magic?

### ISSUE THREAD

**Issue by ecrooks** [catherinedevlin/ipython-sql#122]
I think CTEs do not appear to work. I'm using it with Db2, and I get this error:
![image](https://user-images.githubusercontent.com/9733903/44152174-0cd1cf38-a062-11e8-9ef7-dfdd773aa145.png)

The same query works just fine from the command line, and a similar query without a CTE works just fine in the next cell down in the Jupyter Notebook.

**Comment by ecrooks** [comment]
Never mind, my mistake, got it to work.

**Comment by ecrooks** [comment]
It didn't like starting a line with ) for some reason. Put the ) on the previous line, and it was fine.
![image](https://user-images.githubusercontent.com/9733903/44152907-f43a552e-a063-11e8-8b19-0234cbc1a341.png)

**Comment by catherinedevlin** [comment]
Thanks for posting the followup!

I'm actually surprised it worked at all; `= %sql` is for single-line SQL statements.  For capturing the result of multi-line SQL, I'd use 

```%%sql test_query << with tables as 
    ( select tabname, card...```
