### ISSUE TITLE
How to enable load extension?

### ISSUE THREAD

**Issue by aborruso** [catherinedevlin/ipython-sql#135]
Hi,
I would like to run `connection.enable_load_extension(True)` because I need to run

```
%%sql
SELECT load_extension('/usr/lib/mod_spatialite.so');
```

If I do not enable it, I have `(sqlite3.OperationalError) not authorized`. How load sql ext, and then run `enable_load_extension(True)`?

Thank you

**Comment by kota7** [comment]
This is a bit hacky but is the only solution I could find.

```python
import sql
%load_ext sql

%sql sqlite:///geodb.db
sql.connection.Connection.current.session.connection.enable_load_extension(True)
%sql select load_extension('mod_spatialite.so')
%sql select astext(st_geomfromtext('point(1 2)')) as pt
```
Tested on a kaggle notebook (https://www.kaggle.com/kotamori/use-spatialite-with-ipython-sql).

Some details:

- `%sql` magic is provided in the package named `sql` and is imported here.
- `sql.connection.Connection` stores the set of connections.  `current` is the current default connection.  You can also access other connections by `sql.connection.Connection.connections["connection name"]`
- `session` is an outcome of sqlalchemy's `engine.connect()`.  This is an abstraction of various connection APIs.
- `session.connection` points finally to the underlying sqlite connection object. We call the `enable_load_extension` method to it.

References:

- https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=connection#dbapi-connections
- https://github.com/catherinedevlin/ipython-sql/blob/master/src/sql/connection.py#L54

**Comment by aborruso** [comment]
Wow @kota7 it's a great present, thank you

**Comment by chrinne** [comment]
I join in: many thanks! Had to replace TRUE with 1 but than it worked.
