### ISSUE TITLE
Improve PERSIST

### ISSUE THREAD

**Issue by gbrault** [catherinedevlin/ipython-sql#159]
Today PERSIST fails if table exists and cannot append data to an existing table.

[see code here](https://github.com/catherinedevlin/ipython-sql/blob/9db062c205f1b27c69f5dd3f3f30d50229633a28/src/sql/magic.py#L175)

If transformed like 
`frame.to_sql(table_name, conn.session.engine,if_exists='append')`

It would allow appending to an existing table

**Comment by catherinedevlin** [comment]
Thanks for the PR that implemented this!  It's out in 0.4.0 as of today.
