### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by afeld** [catherinedevlin/ipython-sql#162]
👋 @catherinedevlin! Just used this to do some analysis for a work project (💪 🖥 🇺🇸), and this project was super useful. [Wrote up a thing about it.](https://gist.github.com/afeld/0feb015e329c20b2f5682ca028e3374d)

Anyway, I'm loading a Pandas DataFrame into an in-memory SQLite, and was confused why `--persist` wasn't working. I was referring to the GitHub README, not realizing that the released version (0.3.9) uses `PERSIST`. Anyway, just curious if you're planning to cut a release soon, and wanted to suggest that you either keep that backwards compatible or cut a major release.

Thanks for the awesome tool!

**Comment by grantjenks** [comment]
+1 for new release. I need to use the SqlMagic.displaycon setting. Thanks for this project!

**Comment by jamesjnadeau** [comment]
@catherinedevlin 2nd this request!
I'll do anything I can to help!
Do you need a PR?
❤️ this project, thanks so much for it!

**Comment by catherinedevlin** [comment]
@afeld!  HI!  Good to hear from you!  So glad the package has been helpful!

Sorry everybody for the absurdly long delays - released 0.4.0 this morning.
