### ISSUE TITLE
Support the use of SQL linter/formatter

### ISSUE THREAD

**Issue by flaviomartins** [catherinedevlin/ipython-sql#238]
Is there any chance of supporting automatic linting as well as automatic formatting for SQL code in %%sql cell magic?

Tools such as sqlfluff, that support setting the SQL dialect for checking could be configured on a per-connection basis or set automatically by making an educated guess from the (active) connection string.

I would be using this feature to improve my university-level database course.

thanks for your time

**Comment by idomic** [comment]
@flaviomartins Please feel free to share feedback [here](https://github.com/ploomber/jupysql-plugin/issues/5)
