### ISSUE TITLE
Getting syntax error when trying to use %%sql

### ISSUE THREAD

**Issue by sstorie** [catherinedevlin/ipython-sql#49]
I'm trying to run a simple multi-line query, but am getting a syntax error for any line with `%%sql`:

```
## Run an in-line query
#
%sql select getdate()

## Run a multi-line query
#
%%sql SELECT GETDATE()
```

>  File "<ipython-input-6-896ba75794ad>", line 7
>    %%sql SELECT GETDATE()
>    ^
> SyntaxError: invalid syntax

I can connect fine using `%sql` and can run the single line query without issue, so is there something obvious I'm missing here?

*Note, I'm running the latest code from master because I needed the fix provided by https://github.com/catherinedevlin/ipython-sql/pull/40*

**Comment by stonebig** [comment]
shouldn't `%%sql`be the first 5 characters of your cell ? (if so, you may remove earlier comments)

**Comment by sstorie** [comment]
Yep, that was it! It wasn't clear to me that it needed to be the first characters in the cell.
