### ISSUE TITLE
How-to: a multiline query inside a for loop

### ISSUE THREAD

**Issue by aborruso** [catherinedevlin/ipython-sql#82]
Hi,
first of all thank you ipython-sql is a small treasure!

Is it possible to do in python something like:

```python
list=[1,2]
for i in list:
    %%sql update "table" 
    set fieldA = 12
    where fieldB=:i;
```

Thank you

**Comment by younglee23** [comment]
Hi aborruso,

You are trying to use cell magic (%%sql) which will treat the whole cell as a multi-line sql statement.  I believe you want to use line magic (%sql) to embed the query inside of code within a cell - the challenge is that you need to have the sql statement on a single line.  To get around this (and use mutliple lines) you may use Python's line continuation by ending a line with the backslash character.

I believe your code could look something like this:

```python
list=[1,2]
for i in list:
    %sql update "table" \
    set fieldA = 12 \
    where fieldB=:i;
```

Hope this helps.

**Comment by aborruso** [comment]
Thank you very much
