### ISSUE TITLE
Support for Django's DJANGO_SETTINGS_MODULE

### ISSUE THREAD

**Issue by D3f0** [catherinedevlin/ipython-sql#84]
I have used this extension for some years and mostly in Django projects when I need complex queries. Although I have a base notebook that I copy and paste with the DB settings, it would be nice to retrieve config from settings module itself rather than doing a `%sql xxxx://yyyy@zzz/db`.
Would it pollute the code too much to add support for Django specific DB settings? The name of the settings is stored in `DJANGO_SETTINGS_MODULE` and in that module, they look like this:

https://docs.djangoproject.com/en/1.11/ref/settings/#databases

Thank you!

**Comment by catherinedevlin** [comment]
As a stopgap, the development trunk now supports the $DATABASE_URL environment variable, as per https://github.com/kennethreitz/dj-database-url

**Comment by D3f0** [comment]
I had not given attention to the environment variable, I could solve this issue by running the following code previous to the `%sql` cells.
```
import os
DATABASE_URL = 'postgres://{USER}:{PASSWORD}@{HOST}/{NAME}'.format(**settings.DATABASES['default'])
os.environ['DATABASE_URL'] = DATABASE_URL
```
