### ISSUE TITLE
Will ipython-sql support JDBC drivers?

### ISSUE THREAD

**Issue by dclong** [catherinedevlin/ipython-sql#90]
SQLalchemy requires ODBC which is a hassle to install for commercial databases. Other the other hand, JDBC drivers are much easier to use. Will iptyon-sql support JDBC drivers in future?

**Comment by catherinedevlin** [comment]
Sorry, I'm really dependent on SQLAlchemy, and don't have nearly the chops to build an alternative to it - %sql is, by design, really just a wrapper around SQLAlchemy.  If SQLAlchemy itself gets JDBC support and there's a problem using it there, definitely file a new issue.
