### ISSUE TITLE
how to pass a list in a query

### ISSUE THREAD

**Issue by simonegabbriellini** [catherinedevlin/ipython-sql#92]
I tried to post on [SO](https://stackoverflow.com/questions/45112501/how-to-use-python-list-in-sql-query) with no avail, so I am trying here... 

I know how to pass a parameter to %sql using the ":" syntax, but how do you proceed if you have a list?

Basically, my issue is how to do a query like:

    SELECT * FROM mytable WHERE id IN (12345,576576,678678)

I have the values in a Python list, but don't understand how to pass the list to the query in a proper way... if I do something like:

   people='\',\''.join(str(e) for e in usernumbers)

I get only the first number used and the rest is cut with this warning message:

    /Users/digitaldust/anaconda/lib/python3.6/site-packages/pymysql/cursors.py:166: Warning: (1292, "Truncated incorrect DOUBLE value: '12345','576576','678678'")
    result = self._query(query)

**Comment by simonegabbriellini** [comment]
ok I managed to understand it, say your list is named mylist, then:

    mystring = '({})'.format(','.join(str(e) for e in mylist))

transforms the list into a string and then you call the variable as $mystring within the query

**Comment by audy** [comment]
@simonegabbriellini that example isn't working for me. I believe the syntax has changed (`$` interpolation isn't described in the readme.

This would be useful. Is this type of query supported currently?
