### ISSUE TITLE
using a list as a bind variable

### ISSUE THREAD

**Issue by vinnyp** [catherinedevlin/ipython-sql#98]
I'd like to use a list as a bind variable in a SQL query. I've tried a few tricks but I couldn't get it to work properly.

**Use Case** 
I have a few scenarios where I'll need to pull a column of data from a dataframe and will need to use that data as input in a query. 

`prop_list = [17330224, 92908108, 3364309, 4752144, 710842, 4212297]`

```
%%sql vinny@prod df_serviceregions <<
SELECT
    sr.property_id, sr.service_region_id
FROM
    service_regions sr
WHERE
    sr.is_active AND  
    property_id in(:prop_list)
```

**When I run this, I get the following error:**
```
(psycopg2.ProgrammingError) operator does not exist: bigint = integer[]
LINE 1: ) WHERE sr.is_active AND property_id in(ARRAY[1...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: 'SELECT sr.property_id, sr.service_region_id  FROM service_regions sr WHERE sr.is_active AND property_id in(%(prop_list)s)'] [parameters: {'prop_list': [17330224, 92908108, 3364309, 4752144, 710842, 4212297]}]
```

**Comment by vinnyp** [comment]
Resolving.

Changing `property_id in(:prop_list)` to `property_id = ANY(:prop_list)` solved the issue.

[http://initd.org/psycopg/docs/usage.html#adapt-list](http://initd.org/psycopg/docs/usage.html#adapt-list)

**Comment by cakraww** [comment]
`property_id in :prop_list` should work (removing parentheses)
